In [1]:
### Que 1

### Write a function so that the columns of the output matrix are powers of the input vector.
### The order of the powers is determined by the increasing boolean argument. Specifically, when
### increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

## HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
## Theophile Vandermonde.


In [3]:
import numpy as np 
def atv_matrix(ipvector, n, flag=False):
    
    if not flag:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif flag:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

ip = np.array([1,2,3,4,5])
count=3
#len(ip)
dec_order = atv_matrix(ip,count,False)
inc_order = atv_matrix(ip,count,True)

print("If Increasing True")
print(inc_order)
print("If Increasing False")
print(dec_order)

If Increasing True
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
If Increasing False
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [4]:
## Write a function to find moving average in an array over a window:
## Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
## Note: Solution submitted via github must contain all the detailed steps.

In [6]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

ip=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
ip1=np.array(ip)
np.array(moving_average(ip1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])