In [6]:
## Que 1
## Write a Python program to get the string from the given string where all the occurrence of its
## first char has been changed to '$,' except first char itself? 

 ## Sample String: 'prospect' 
 ## Expected Result : 'pros$ect'

In [7]:
sample_string='prospect'
char=sample_string[0]
result_string=sample_string.replace(char,'$')
result_string=char + result_string[1:]
result_string

'pros$ect'

In [ ]:
### Que 2
 ## Write a Python program to get the single string from the two given strings, and separated by the 
## space and swap the first two characters of each string? 

## Sample String : 'abc', 'xyz'. 
## Expected Result: 'xyc abz'

In [8]:
s1='abc'
s2='xyz'
new_a = s2[:2] + s1[2:]
new_b = s1[:2] + s2[2:]

swap_string = new_a+ ' ' + new_b

print(swap_string)

xyc abz


In [9]:
## Que 3
## Write the Python program to add 'ing' at the end of the given string (length of the string should be at least 3). 
## If given string already ends with 'ing,' then add 'ly' instead. If string length of the given string is less than 3,
## leave it unchanged?
## Sample string: ' abc ' 
## Expected result: ' abcing ' 
## Sample string: ' string ' 
## Expected result: ' stringly '

In [5]:
def add_string(str1):
  length = len(str1)

  if length > 2:
    if str1[-3:] == 'ing':
      str1 += 'ly'
    else:
      str1 += 'ing'

  return str1
#print(add_string('ab'))
print(add_string('abc'))
print(add_string('string'))

abcing
stringly


In [10]:
## Que 4
## Q4. Write the Python program to find the first appearance of the substring 'not' and 'poor' from the given string, 
## if 'not' follows the 'poor', replace the whole 'not'...' poor' substring with 'good'.Return the resulting string.
## Sample string: 'The lyrics are not that poor!' 
## 'The lyrics are poor!' 
## Expected Result:  'The lyrics are good!' 
## 'The lyrics are poor!'

In [11]:
def not_poor(str1):
  snot = str1.find('not')
  spoor = str1.find('poor')
  

  if spoor > snot and snot>0 and spoor>0:
    str1 = str1.replace(str1[snot:(spoor+4)], 'good')
    return str1
  else:
    return str1

    

print(not_poor('The lyrics are not that poor!'))
print(not_poor('The lyrics are poor!'))


The lyrics are good!
The lyrics are poor!


In [12]:
## Que 5
##  Write the Python program to remove the characters which have odd index values of a given string

In [13]:
str1 = input("Please Enter your Own String : ")

str2 = ''

for i in range(len(str1)):
    if(i % 2 == 0):
        str2 = str2 + str1[i]
        
print("Original String :  ", str1)
print("Final String :     ", str2)


Please Enter your Own String : abcdef'
Original String :   abcdef'
Final String :      ace'


In [15]:
### Que 6

## Write the Python function to get a string made of 4 copies of the last two characters of the specified
## string (length must be at least 2).

## Sample function and result : 

## insert-end ('Python') -> abababab 
## insert-end('Exercises') -> jkjkjkjk

In [26]:
str1=input()
str2=input()
sub_string1= str1[-2:]*4
sub_string2=str2[-2:]*4
print('-' *10)
print(sub_string1)
print(sub_string2)



python
exercise
----------
onononon
sesesese


In [27]:
## Que 7

## Write the python function to get a string made of its first three characters of a specified string.
## If the length of the string is less than 3 then return the original string.

## Sample function and result : 
## first-three('ipy') -> ipy
## first-three('python') -> pyt

In [29]:
str1=input()
str2=input()
sub_string1= str1[:3]
sub_string2=str2[:3]
print('-' *10)
print(sub_string1)
print(sub_string2)



ipy
python
----------
ipy
pyt


In [30]:
## Que 8
## Write the python program to print the following floating numbers up to 2 decimal places?

In [45]:
x = 3.1415926
y = 12.9999
print("Formatted no is:",round(x,2))      ## this is round off  no
print("Formated no is:",'%.2f'%y)        ### this is also round off the no
print ("Formatted no is:","{0:.2f}".format(y)) 

Formatted no is: 3.14
Formated no is: 13.00
Formatted no is: 13.00


In [47]:
### Que 9

###  Write the Python program to format a number with a percentage? 


In [53]:
x =0.27
print ("Formatted no is:","{:.0%}".format(x))

print ("Formatted no is:","{0:.2%}".format(x)) 

Formatted no is: 27%
Formatted no is: 27.00%


In [54]:
### Que 10

## Write the Python program to count occurrences of a substring in a String?

In [56]:
string="Data Science is the most Demanding field of the World "
print(string.count("the"))


2


In [1]:
## Que 11
## Write the Python program to count repeated characters in a string.

## Sample string: ' thequickbrownjumpsoverthelazydog ' 
## Expected output: o 3 
#                   e 3 
#                   u 2
#                   h 2
#                   r 2
#                   t 2

In [66]:
import collections
str1 = 'thequickbrownjumpsoverthelazydog'
d = collections.defaultdict(int)
for c in str1:
    d[c] += 1

for c in sorted(d, key=d.get, reverse=True):
  if d[c] > 1:
      print('%s %d' % (c, d[c]))       ### or you can use %i instead of %d

e 3
o 3
t 2
h 2
u 2
r 2


In [68]:
### Que 12
## Write the Python program to print the square and cube symbol in the area of a rectangle and volume of a cylinder? 

## Sample output- The area of the rectangle is 1256.66cm2 
##                The volume of the cylinder is 1254.725cm3


In [100]:
area = 1256.66
volume = 1254.725
decimals = 2
print("The area of the rectangle is {0:.{1}f}cm\u00b2".format(area, decimals))
decimals = 3
print("The volume of the cylinder is {0:.{1}f}cm\u00b3".format(volume, decimals))


The area of the rectangle is 1256.66cm²
The volume of the cylinder is 1254.725cm³


In [ ]:
##  Que 13
## Write the Python program to check if a string contains all letters of the alphabet?


In [113]:
import string
alphabet = set(string.ascii_lowercase)
input_string = 'The quick brown fox jumps over the lazy dog'
print(set(input_string.lower()) >= alphabet)
input_string = 'The quick brown fox jumps over the lazy cat'
print(set(input_string.lower()) <= alphabet)


True
False


In [114]:
## Que 14
## Write the Python program to find the second most repeated word in a given string

In [138]:
def word_count(str):
    counts = dict()
    words = str.split()
    #print(words)

    for word in words:
        if word in counts:
            #print(word
            #print(counts[word])
            counts[word] += 1
        else:
            counts[word] = 1
            

    counts_x = sorted(counts.items(),key=lambda kv: kv[1])
    #print(counts_x)
    return counts_x[-2]
 
print(word_count("Both of these issues are fixed by postponing the evaluation of annotations. Instead of compiling code which executes expressions in annotations at their definition time, the compiler stores the annotation in a string form equivalent to the AST of the expression in question. If needed, annotations can be resolved at runtime using typing.get_type_hints(). In the common case where this is not required, the annotations are cheaper to store (since short strings are interned by the interpreter) and make startup time faster."))

('of', 4)


In [139]:
### Que 15
## Write the Python program to find the minimum window in the given string, which will contains all the characters of 
## another given strings?
# Example 1
## Input : string1 = " PRWSOERIUSFK " 
## string2 = " OSU " 
## Output: Minimum window is "OERIUS"

In [19]:
import collections
def min_window(str1, str2):
    result_char, missing_char = collections.Counter(str2), len(str2)
    i = p = q = 0
    for j, c in enumerate(str1, 1):
        missing_char -= result_char[c] > 0
        result_char[c] -= 1
        if not missing_char:
            while i < q and result_char[str1[i]] < 0:
                result_char[str1[i]] += 1
                i += 1
            if not q or j - i <= q - p:
                p, q = i, j
    return str1[p:q]
           
str1 = "PRWSOERIUSFK"
str2 = "OSU"
print("Original Strings:\n",str1,"\n",str2)
print("Minimum window:")
print(min_window(str1,str2))


Original Strings:
 PRWSOERIUSFK 
 OSU
Minimum window:
OERIUS


In [22]:
## Que 16
## Write the Python program to find smallest window that contains all characters of the given string?

## Original Strings: asdaewsqgtwwsa
## Smallest window that contains all characters of the said string:
## Daewsqgtfrom collections import defaultdict   


In [23]:
from collections import defaultdict   

def find_sub_string(str): 
    str_len = len(str) 
      
    # Count all distinct characters. 
    dist_count_char = len(set([x for x in str])) 
  
    ctr, start_pos, start_pos_index, min_len = 0, 0, -1, 9999999999
    curr_count = defaultdict(lambda: 0) 
    for i in range(str_len): 
        curr_count[str[i]] += 1
 
        if curr_count[str[i]] == 1: 
            ctr += 1
  
        if ctr == dist_count_char: 
            while curr_count[str[start_pos]] > 1: 
                if curr_count[str[start_pos]] > 1: 
                    curr_count[str[start_pos]] -= 1
                start_pos += 1
  
            len_window = i - start_pos + 1
            if min_len > len_window: 
                min_len = len_window 
                start_pos_index = start_pos 
    return str[start_pos_index: start_pos_index + min_len] 
      
str1 = "asdaewsqgtwwsa"
print("Original Strings:\n",str1)
print("\nSmallest window that contains all characters of the said string:")
print(find_sub_string(str1)) 

Original Strings:
 asdaewsqgtwwsa

Smallest window that contains all characters of the said string:
daewsqgt


In [24]:
### Que 17
## Write the Python program to count number of substrings from a given string of lowercase alphabets 
## with exactly k distinct (given) characters?

#    Input a string (lowercase alphabets): wolf 
#    Input k: 4 
#    Number of substrings with exactly 4 distinct characters: 1

In [4]:
def count_k_dist(str1, k): 
    str_len = len(str1)
    

    result = 0

    ctr = [0] * 27
    #print(ctr)

    for i in range(0, str_len): 
        dist_ctr = 0

        ctr = [0] * 27

        for j in range(i, str_len): 
            #print(j)

            if(ctr[ord(str1[j]) - 97] == 0): 
                dist_ctr += 1

        ctr[ord(str1[j]) - 97] += 1

        if(dist_ctr == k): 
            result += 1
        if(dist_ctr > k): 
             break

    return result 

str1 = input("Input a string (lowercase alphabets):")
k = int(input("Input k: "))
print("Number of substrings with exactly", k, "distinct characters : ", end = "") 
print(count_k_dist(str1, k))

Input a string (lowercase alphabets):wolf
Input k: 4
Number of substrings with exactly 4 distinct characters : 1


In [5]:
### Que 18
## Write the Python program to count number of non-empty substrings of the given string

## Input a string: w3schools
## Number of substrings: 55

In [10]:
def number_of_substrings(str): 
    str_len = len(str1)
    return int(str_len * (str_len + 1) / 2); 

str1 = input("Input a string: ")
print("Number of substrings:") 
print(number_of_substrings(str1))
print(len(str1))

Input a string: geeksforgeeks
Number of substrings:
91
13


In [11]:
### Que 19
## Write the Python program to count number of substrings with same first and last characters of the given string?

## Input a string: abcd 
## 4

In [20]:
def no_of_substring_with_equalEnds(str1): 
    result = 0; 
    n = len(str1)
    for i in range(n): 
        #print(i)
        for j in range(i, n): 
            #print(j)
            if (str1[i] == str1[j]): 
                result = result + 1
                #print(result)
    return result 
str1 = input("Input a string: ")
print(no_of_substring_with_equalEnds(str1))

Input a string: abcd
4


In [ ]:
### Que 20
## Write the Python program to count the number of strings where the string length is 2 or more,
## and first and last character are same from a given list of strings.

## Sample List : ['abc', 'xyz', 'wxw', '1331'] 
## Expected Result: 2

In [30]:
def match_words(words):
  ctr = 0

  for word in words:
    #print(word)
    #print(word[0])
    #print(word[-1])
    if len(word) > 1 and word[0] == word[-1]:
      ctr += 1
  return ctr

print(match_words(['abc', 'xyz', 'aba', '1221']))

2


In [32]:
### Que 21
## Write the Python program to get a list, sorted in increasing order by the last element in each
## tuple from the given list of non-empty tuples?

## Sample List - [ (2, 5), (1, 2), (4, 4), (2, 3), (2, 1) ] 
## Expected Result - [ (2, 1), (1, 2), (2, 3), (4, 4), (2, 5) ]

In [40]:
def last(n): 
    return n[-1]
    print(n[-1])

def sort_list_last(tuples):
  return sorted(tuples, key=last)

print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))


[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [41]:
### Que 22
## Write the Python program to remove duplicates from a list?


In [53]:
from collections import OrderedDict
def remove_duplicate(str1):
  return "".join(OrderedDict.fromkeys(str1))
     
print(remove_duplicate("python subjective practice question"))
print(remove_duplicate("geeksforgeeks"))
OrderedDict.fromkeys

python subjecivraq
geksfor


<function OrderedDict.fromkeys(iterable, value=None)>

In [54]:
### Que 23
## Write the Python program to find the list of words that are longer than n from a given list of words?

In [55]:
def long_words(n, str):
    word_len = []
    txt = str.split(" ")
    for x in txt:
        if len(x) > n:
            word_len.append(x)
    return word_len	
print(long_words(3, "The quick brown fox jumps over the lazy dog"))


['quick', 'brown', 'jumps', 'over', 'lazy']


In [61]:
### Que 24
## Write the Python program to print a specified list after removing the 0th, 4th, and 5th elements?

## Sample List - ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow'] 
## Expected Output - ['Green', 'White', 'Black']

In [62]:
color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
color = [x for (i,x) in enumerate(color) if i not in (0,4,5)]
print(color)

['Green', 'White', 'Black']


In [63]:
### Que 25
## Write the Python program to generate all permutations of a list in Python?

In [65]:
import itertools
print(list(itertools.permutations([1,2,3])))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [1]:
### Que 26
## Write the Python program to convert a pair of values into a sorted   unique array?               

# Original List-  [ (1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10) ]              
# Sorted Unique Data- [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]   
 

In [2]:
L = [(1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4),
 (7, 8), (9, 10)]
print("Original List: ", L)
print("Sorted Unique Data:",sorted(set().union(*L)))

Original List:  [(1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10)]
Sorted Unique Data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
#Q27.  Write the Python class to convert an integer to a roman numeral? 

In [5]:
class roman:
    def int_to_Roman(self, num):
        val = [
            1000, 900, 500, 400,
            100, 90, 50, 40,
            10, 9, 5, 4,
            1
            ]
        syb = [
            "M", "CM", "D", "CD",
            "C", "XC", "L", "XL",
            "X", "IX", "V", "IV",
            "I"
            ]
        roman_num = ''
        i = 0
        while  num > 0:
            for _ in range(num // val[i]):
                roman_num += syb[i]
                num -= val[i]
            i += 1
        return roman_num

R=roman()
N=int(input('Enter the number'))
print(R.int_to_Roman(N))

Enter the number4
IV


In [6]:
#Q28. Write the Python class to convert a Roman numeral to an integer? 

In [7]:
class roman:
    def roman_to_int(self, s):
        rom_val = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
        int_val = 0
        for i in range(len(s)):
            if i > 0 and rom_val[s[i]] > rom_val[s[i - 1]]:
                int_val += rom_val[s[i]] - 2 * rom_val[s[i - 1]]
            else:
                int_val += rom_val[s[i]]
        return int_val

    
R=roman()
N=input('Enter the Roman letter  ')
print(R.roman_to_int(N))

Enter the Roman letter  DMM
1500


In [8]:
#Q29. Write the Python class to find  the validity of the string of the parentheses, '(', ')', '{', '}', '[' and '] and 
#the brackets must be closed  in the correct order, example - "()" and "()[]{}" are valid but "[)", "({[)]" 
#and "{{{" are invalid.  
 

In [9]:
class myfun:
   def is_valid_parenthese(self, str1):
        stack, pchar = [], {"(": ")", "{": "}", "[": "]"}
        for parenthese in str1:
            if parenthese in pchar:
                stack.append(parenthese)
            elif len(stack) == 0 or pchar[stack.pop()] != parenthese:
                return False
        return len(stack) == 0

    
    
R=myfun()    
print(R.is_valid_parenthese("(){}[]"))
print(R.is_valid_parenthese("()[{)}"))
print(R.is_valid_parenthese("()"))

True
False
True


In [10]:
#Q30. Write the Python class to get all possible unique subsets from a set of distinct integers? 
 
#Input - [4, 5, 6]  Output - [[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]] 

In [11]:
class sub:  
    def f1(self, s1):  
        return self.f2([], sorted(s1))  
 
    def f2(self, curr, s1):  
        if s1:  
            return self.f2(curr, s1[1:]) + self.f2(curr + [s1[0]], s1[1:])  
        return [curr]  
a=[]
#n=int(input("Enter number of elements of list: "))
for i in range(0,3):
    b=int(input("Enter element: "))
    a.append(b)
print("Subsets: ")
print(sub().f1(a))

Enter element: 4
Enter element: 5
Enter element: 6
Subsets: 
[[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]]


In [12]:
#Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array 
# whose sum equals the specific target number?    
#Input: numbers- [10,20,10,40,50,60,70], target=50 Output- 3, 4 

In [13]:
class myfun:
   def Sum(self, nums, target):
        lookup = {}
        #i=1
        for i, num in enumerate(nums):
            if target - num in lookup:
                return (lookup[target - num], i )
            lookup[num] = i
            
R=myfun() 
print("index 1= %d, index 2=  %d" % R.Sum((10,20,10,40,50,60,70),50))

index 1= 2, index 2=  3


In [14]:
#Q32. Write the Python class to find the three elements that sum to zero from the set of n real numbers? 
 
#Input array- [-25, -10, -7, -3, 2, 4, 8, 10] Output - [[-10, 2, 8], [-7, -3, 10]] 

In [15]:
class myfun:
 def findTriplets(self, nums):
        nums, result, i = sorted(nums), [], 0
        while i < len(nums) - 2:
            j, k = i + 1, len(nums) - 1
            while j < k:
                if nums[i] + nums[j] + nums[k] < 0:
                    j += 1
                elif nums[i] + nums[j] + nums[k] > 0:
                    k -= 1
                else:
                    result.append([nums[i], nums[j], nums[k]])
                    j, k = j + 1, k - 1
                    while j < k and nums[j] == nums[j - 1]:
                        j += 1
                    while j < k and nums[k] == nums[k + 1]:
                        k -= 1
            i += 1
            while i < len(nums) - 2 and nums[i] == nums[i - 1]:
                i += 1
        return result

R=myfun()
print(R.findTriplets([-25, -10, -7, -3, 2, 4, 8, 10]))

[[-10, 2, 8], [-7, -3, 10]]


In [16]:
#Q33.  Write the Python class to implement pow(x, n)? 

In [17]:
class power:
   def pow(self, x, n):
        if x==0 or x==1 or n==1:
            return x 

        if x==-1:
            if n%2 ==0:
                return 1
            else:
                return -1
        if n==0:
            return 1
        if n<0:
            return 1/self.pow(x,-n)
        val = self.pow(x,n//2)
        if n%2 ==0:
            return val*val
        return val*val*x
    
R=power()
print(R.pow(2, -3));
print(R.pow(3, 5));

0.125
243


In [18]:
#Q34. Write the Python class which has two methods get_String and  print_String. 
#get_String accept the string from the user and   
#print_String print the string in upper case

In [21]:
class mystring():
    def __init__(self):
        self.str1 = ""

    def get_String(self):
        self.str1 = input('Enter the string')

    def print_String(self):
        print(self.str1.upper())

str1 = mystring()
str1.get_String()
str1.print_String()

Enter the stringShruti Katre
SHRUTI KATRE


In [20]:
#Q35. Write the Python class named Rectangle constructed by a length 
#and width and the method which will compute the area of the rectangle? 

In [22]:
class Rectangle():
    def __init__(self, l, w):
        self.length = l
        self.width  = w

    def rectangle_area(self):
        return self.length*self.width

l=int(input('Enter the lenght'))
w=int(input('Enter the width'))
R = Rectangle(l, w)
print(R.rectangle_area())

Enter the lenght5
Enter the width5
25


In [23]:
#Q36.Write the Python class named Circle constructed by the radius   
#and two methods which will compute the area and perimeter of the circle? 

In [26]:
class Circle():
    def __init__(self, r):
        self.radius = r

    def area(self):
        return self.radius**2*3.14
    
    def perimeter(self):
        return 2*self.radius*3.14

r=int(input('Enter the radius:- '))
R= Circle(r)
print(R.area())
print(R.perimeter())

Enter the radius:- 4
50.24
25.12


In [27]:
#Q37. Write the Python program to get the class name of an instance in Python?

In [28]:
class Circle():
    def __init__(self, r):
        self.radius = r

    def area(self):
        return self.radius**2*3.14
    
    def perimeter(self):
        return 2*self.radius*3.14

r=int(input('Enter the radius'))
R= Circle(r)
print(R.area())

print(type(R).__name__)

Enter the radius4
50.24
Circle


In [29]:
#Q38. Write the Python program to count the number of students of individual class? Sample data 

#classes = ( ('V', 1), ('VI', 1), ('V', 2), ('VI', 2), ('VI', 3), ('VII', 1), ) 

#Expected Output- Counter({'VI': 3, 'V': 2, 'VII': 1}) 

In [30]:
from collections import Counter
classes = (
    ('V', 1),
    ('VI', 1),
    ('V', 2),
    ('VI', 2),
    ('VI', 3),
    ('VII', 1),
)
students = Counter(class_name for class_name, no_students in classes)
print(students)

Counter({'VI': 3, 'V': 2, 'VII': 1})


In [31]:
#Q39. Write the Python program to create an instance of an OrderedDict using the given dictionary and sort dictionary during the 
#creation and print members of the dictionary in reverse order?   
#Expected Output- Angola 244. Andorra 376. Algeria 213. Afghanistan 93. Albania 355. In reverse order- Albania  355. Afghanistan  93. Algeria  213. Andorra  376. Angola  244.

In [33]:
from collections import OrderedDict
dict = {'Afghanistan': 93, 'Albania': 355, 'Algeria': 213, 'Andorra': 376, 'Angola': 244}
new_dict = OrderedDict(dict.items())
for key in new_dict:
    print (key, new_dict[key])

print("\nIn reverse order:")
for key in reversed(new_dict):
    print (key, new_dict[key])

Afghanistan 93
Albania 355
Algeria 213
Andorra 376
Angola 244

In reverse order:
Angola 244
Andorra 376
Algeria 213
Albania 355
Afghanistan 93


In [34]:
#Q40. Write the Python program to compare two unordered lists (not sets)? 
 
    #Expected Output: False

In [35]:
n1 = [20, 10, 30, 10, 20, 30]
n2 = [30, 20, 10, 30, 20, 50]
n1.sort()
n2.sort()
n1==n2

False

In [36]:
# Q41. Write the Python program to get an array buffer information? 
# Expected Output- Array buffer start address in memory and number of elements. (25855056, 2) 

In [43]:
from array import array
a = array("i", [57,43])
print("Array buffer start address in memory and number of elements.")
print(a.buffer_info())

Array buffer start address in memory and number of elements.
(2587213114992, 2)


In [44]:
#Q42.Write the Python program to convert an array to an array of machine values and return the bytes representation?
#Expected Output- Original array- A1: array('i', [1, 2, 3, 4, 5, 6]) 
#Array of bytes: b'010000000200000003000000040000000500000006000000

In [45]:
import array
import binascii
a = array.array('i', [1,2,3,4,5,6])
print("Original array:")
print('A1:', a)
bytes_array = a.tobytes()
print('Array of bytes:', binascii.hexlify(bytes_array))

Original array:
A1: array('i', [1, 2, 3, 4, 5, 6])
Array of bytes: b'010000000200000003000000040000000500000006000000'


In [46]:
#Q43. Write the Python program to read a string and interpreting the   string as an array of machine values? 
 
#Expected Output- array1- array('i', [7, 8, 9, 10]) Bytes- b'0700000008000000090000000a000000' 
#array2- array('i', [7, 8, 9, 10]) 

In [47]:
from array import array
import binascii
array1 = array('i', [7, 8, 9, 10])
print('array1:', array1)
as_bytes = array1.tobytes()
print('Bytes:', binascii.hexlify(as_bytes))
array2 = array('i')
array2.frombytes(as_bytes)
print('array2:', array2)

array1: array('i', [7, 8, 9, 10])
Bytes: b'0700000008000000090000000a000000'
array2: array('i', [7, 8, 9, 10])


In [48]:
#Q44. Write the Python program to push three items into the heap and   return the smallest item from the heap. Also, return and pop the   smallest item from the heap?  
 
#Expected Output- Items in the heap- ('VI', 1). ('VII', 3). ('VIII', 2). ----------------------
#The smallest item in the heap: ('VI', 1). 
  #---------------------- Pop the smallest item in the heap: ('VII', 2). ('VIII', 3). 

In [49]:
import heapq
heap = []
heapq.heappush(heap, ('V', 3))
heapq.heappush(heap, ('V', 2))
heapq.heappush(heap, ('V', 1))
print("Items in the heap:")
for a in heap:
	print(a)
print("----------------------")
print("The smallest item in the heap:")
print(heap[0])
print("----------------------")
print("Pop the smallest item in the heap:")
heapq.heappop(heap)
for a in heap:
	print(a)


Items in the heap:
('V', 1)
('V', 3)
('V', 2)
----------------------
The smallest item in the heap:
('V', 1)
----------------------
Pop the smallest item in the heap:
('V', 2)
('V', 3)


In [50]:
#Q45. Write the Python program to locate the left insertion point for a specified value in sorted order?  
#Expected Output: 4 2 

In [51]:
import bisect
def index(a, x):
    i = bisect.bisect_left(a, x)
    return i
    
a = [1,2,4,5]
print(index(a, 6))
print(index(a, 3))

4
2


In [52]:
#Q46. Write the Python program to create the FIFO queue?  
#Expected Output: 0 1 2 3  

In [53]:
class Queue:
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def enqueue(self, item):
        self.items.insert(0,item)

    def dequeue(self):
        return self.items.pop()

    def size(self):
        return len(self.items)
    
q=Queue()
for x in range(4):
    q.enqueue(str(x))
    
#remove items 
while not q.isEmpty():
    print(q.dequeue(), end=" ")
print("\n")

0 1 2 3 



In [54]:
#Q47. Write the Python program to calculate the harmonic sum of n-1.Note: The harmonic sum is the sum of 
#reciprocals of the positive Integers? 


In [55]:
def sum(n): 
    i = 1
    s = 0.0
    for i in range(1, n+1): 
        s = s + 1/i; 
    return s; 
  
n = 4
print("Sum is", round(sum(n), 6)) 

Sum is 2.083333


In [56]:
#Q48. Write the NumPy program to create a 2d array with 6 on the border and 0 inside? 
 
#Expected Output- Original array- [ [6 6 6 6 6]   [ 6 6 6 6 6]   [ 6 6 6 6 6 ]   [ 6 6 6 6 6 ]   [ 6  6 6 6 ] ]. 
 
#6 on the border and 0 inside in the array- [[ 6 6 6 6 6] [ 6 0 0 0 6] [ 6 0 0 0 6] [ 6 0 0 0 6] [ 6 6 6 6 6]]. 

In [57]:
import numpy as np
x = np.ones((5,5))
y = np.array(x) 
y[y == 1] = 6

print("Original array:")
print(y)
print("6 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
y = np.array(x) 
y[y == 1] = 6
print(y)

Original array:
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
6 on the border and 0 inside in the array
[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


In [58]:
#Q49.  Write the NumPy program to create a 8x8 matrix and fill it with the   checkerboard pattern? 
 
#Checkerboard pattern- 
#[[3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3] [3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3] [3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3] 
# [3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3]]. 

In [59]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
y = np.array(x) 
y[y == 0] = 3
y[y == 1] = 9
print(y)

Checkerboard pattern:
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


In [60]:
#Q50. Write the NumPy program to create an empty and a full array.               
#Expected Output- 
 #[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306] [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308] [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]] [[6 6 6] [6 6 6] [6 6 6]] 

In [61]:
import numpy as np
x = np.empty((3,4))
print(x)
y = np.full((3,3),6)
print(y)

[[1.27825668e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.31370903e-076 5.64041903e-091 4.50235748e+174]
 [5.41702340e-067 8.69524125e-071 3.99910963e+252 1.46030983e-319]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [62]:
### Que 51
## Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and 
## the centigrade values are stored in the NumPy array

# Sample Array -[0, 12, 45.21 ,34, 99.91] 
# Expected Output- Values in Fahrenheit degrees- [ 0. 12. 45.21 34. 99.91] 
# Values in Centigrade degrees- [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [63]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [64]:
### Que 52
## Write the NumPy program to find the real and imaginary parts of an array of complex numbers?

# Expected Output- Original array [ 1.00000000+0.j 0.70710678+0.70710678j] 
# Real part of the array- [ 1. 0.70710678] 
# Imaginary part of the array- [ 0. 0.70710678]

In [65]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)

Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


In [66]:
### Que 53
## Write the NumPy program to test whether each element of a 1-D array is also present in the second array?

## Expected Output- Array1: [ 0 10 20 40 60] 
## Array2: [0, 40] 
## Compare each element of array1 and array2 [ True False False True False]

In [67]:
values_1=[0,10,20,40,60]
Array_1=np.array(values_1)
print("Array1:",Array_1)
values_2=[0,40]
Array_2=np.array(values_2)
print("Array2:",Array_2)
print("Comparison of each element of array1 and array2 :",np.in1d(Array_1, Array_2))


Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
Comparison of each element of array1 and array2 : [ True False False  True False]


In [68]:
### Que 54
## Write the NumPy program to find common values between two arrays?

## Expected Output- Array1: [ 0 10 20 40 60] 
## Array2: [10, 30, 40] 
## Common values between two arrays- [10 40]

In [69]:
import numpy as np
array_1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array_1)
array_2 = [10, 30, 40]
print("Array2: ",array_2)
print("Common values between two arrays:")
print(np.intersect1d(array_1, array_2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [70]:
### Que 55
## Write the NumPy program to get the unique elements of an array?

## Expected Output- Original array- [10 10 20 20 30 30] 
## Unique elements of the above array- [10 20 30]

## Original array- [[1 1] [2 3]] 
## Unique elements of the above array- [1 2 3]

In [71]:
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
print("-" *30)
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
------------------------------
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [72]:
### Que 56
## Write the NumPy program to find the set exclusive-or of two arrays. 
## Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays?

## Array1- [ 0 10 20 40 60 80] Array2- [10, 30, 40, 50, 70] 
## Unique values that are in only one (not both) of the input arrays- [ 0 20 30 50 60 70 80]

In [73]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))


Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [74]:
### Que 57
## Write the NumPy program to test if all elements in an array evaluate to True ?

In [75]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))


False
True
False
True


In [76]:
### Que 58
## Write the NumPy program to test whether any array element along the given axis evaluates to True?

In [77]:
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))


False
True
True
True


In [78]:
### Que 59
## Write the NumPy program to construct an array by repeating?

## Sample array- [1, 2, 3, 4] 
## Expected Output- Original array [1, 2, 3, 4] 
## Repeating 2 times [1 2 3 4 1 2 3 4]
## Repeating 3 times [1 2 3 4 1 2 3 4 1 2 3 4]

In [79]:
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)                ### it repeats the digit n no of times
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)

Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


In [80]:
### Que 60
## Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array?
## Original array- [1 2 3 4 5 6] Maximum Values- 5 Minimum Values- 0

In [81]:
values=[1,2,3,4,5,6]
array=np.array(values)
print(array)
Max=np.argmax(array)  ### argmaz gives then maximum index whereas max gives the maximum number
print("Maximum values:",Max)
Min=np.argmin(array)
print("Minimum values:",Min)

[1 2 3 4 5 6]
Maximum values: 5
Minimum values: 0


In [83]:
### Que 61
## Write the NumPy program compare two arrays using numpy?

## Array a- [1 2]  Array b- [4 5] 
## a > b [False False] 
## a >= b [False False]
## a < b [ True True] 
## a <= b [ True True]

In [84]:
a=np.array([1,2])
print(a)
b=np.array([4,5])
print(b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))



[1 2]
[4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [85]:
### Que 62
## Write the NumPy program to sort an along the first, last axis of an array?

## Sample array- [[2,5],[4,4]] 
## Expected Output- Original array: [[4 6] [2 1]] 
## Sort along the first axis: [[2 1] [4 6]]
## Sort along the last axis- [[1 2] [4 6]]

In [86]:
import numpy as np
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


In [87]:
### Que 63
## Write the NumPy program to sort pairs of first name and last name return 
## their indices (first by last name, then by first name).

## first_names - ( Betsey, Shelley, Lanell, Genesis, Margery ) 
## last_names - ( Battle, Brien, Plotner, Stahl, Woolum ) 
## Expected Output- [1 3 2 4 0]

In [88]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


In [89]:
### Que 64
## Write the NumPy program to get the values and indices of the elements that are bigger than 10 in the given array?

## Original array- [[ 0 10 20] [20 30 40]] 
## Values bigger than 10 = [20 20 30 40] 
## Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [90]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [91]:
### Que 65
## Write the NumPy program to find the memory size of a NumPy array?

## Expected Output- 128 bytes

In [92]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


In [93]:
### Que 66
## Write the NumPy program to create an array of ones and an array of zeros?

## Expected Output- 
## Create an array of zeros Default type is float [[ 0. 0.]] Type changes to int [[0 0]] 
## Create an array of ones Default type is float [[ 1. 1.]] Type changes to int [[1 1]]

In [94]:
import numpy as np
print("Create an array of zeros")
x = np.zeros((1,2))
print("Default type is float")
print(x)
print("Type changes to int")
x = np.zeros((1,2), dtype = np.int)
print(x)
print("Create an array of ones")
y= np.ones((1,2)) 
print("Default type is float")
print(y)
print("Type changes to int")
y = np.ones((1,2), dtype = np.int)
print(y)

Create an array of zeros
Default type is float
[[0. 0.]]
Type changes to int
[[0 0]]
Create an array of ones
Default type is float
[[1. 1.]]
Type changes to int
[[1 1]]


In [95]:
### Que 67
## Write the NumPy program to change the dimension of an array?

## Expected Output- 6 rows and 0 columns (6,) (3, 3) ->
## 3 rows and 3 columns [[1 2 3] [4 5 6] [7 8 9]] 
## Change array shape to (3, 3) -> 3 rows and 3 columns [[1 2 3] [4 5 6] [7 8 9]]

In [96]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
### Que 68
## Write the NumPy program to create a new shape to an array without changing its data ?

## Reshape 3x2- [[1 2] [3 4] [5 6]] 
## Reshape 2x3- [[1 2 3] [4 5 6]]

In [98]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [99]:
### Que 69
## Write the NumPy program to create a new array of 3*5, filled with 2?

## Expected Output- [[2 2 2 2 2] [2 2 2 2 2] [2 2 2 2 2]] [[2 2 2 2 2] [2 2 2 2 2] [2 2 2 2 2]]

In [100]:
import numpy as np
#using np.full
x = np.full((3, 5),2, dtype=np.uint)
print(x)
#using np.ones
y = np.ones([3, 5], dtype=np.uint)*2
print(y)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [101]:
### Que 70
## Write the NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere?

## Expected Output- [[ 1. 0. 0.] [ 0. 1. 0.] [ 0. 0. 1.]]

In [102]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
### Que 71
## Write the NumPy program to split an array of 14 elements into the 3 arrays and each of which has
## 2, 4, and 8 elements in original order?

## Expected Output- Original array- [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14] 
## After splitting- [array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [104]:
import numpy as np
x = np.arange(1, 15)
print("Original array:",x)
#print("After splitting:")
print(np.split(x, [2,6]))


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [105]:
### Que 72
## Write the NumPy program to split of an array of shape 4x4 it into two arrays along the second axis ?

## Sample array - [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11] [12 13 14 15]] 
## Expected Output-[array([[ 0, 1], [ 4, 5], [ 8, 9], [12, 13]]),
#                  array([[ 2, 3], [ 6, 7], [10, 11], [14, 15]]), 
#                  array([], shape=(4, 0), dtype=int64)]

In [106]:
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [107]:
## Que 73
## Write the NumPy program to create a 5x5 matrix with row values ranging from 0 to 4?

## Original array- [[ 0. 0. 0. 0. 0.] [ 0. 0. 0. 0. 0.] [ 0. 0. 0. 0. 0.] [ 0. 0. 0. 0. 0.] [ 0. 0. 0. 0. 0.]] 
## Row values ranging from 0 to 4. [[ 0. 1. 2. 3. 4.] [ 0. 1. 2. 3. 4.] [ 0. 1. 2. 3. 4.] [ 0. 1. 2. 3. 4.] [ 0. 1. 2. 3. 4.]]

In [108]:
import numpy as np
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [109]:
### Que 74
## Write the NumPy program to create an array of zeros and three column types (integer, float, character)?

## Expected Output- [(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley') (3, 3., b'Gertrude B. Elion')]

In [110]:
import numpy as np
x = np.zeros((3,), dtype=('i4,f4,a40'))
#print(x)
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)


[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


In [111]:
### Que 75
## Write the NumPy program to remove the negative values in the numpy array with 0?

## Expected Output- Original array: [-1 -4 0 2 3 4 5 -6] 
## Replace the negative values of the said array with 0- [0 0 0 2 3 4 5 0]

In [112]:
import numpy as np
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x < 0] = 0
print(x)

Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]
